source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.0.4"

gem 'pry'
gem "rails", "~> 7.0.3"
gem "sqlite3", "~> 1.4"
gem "puma", "~> 5.0"
gem "grpc"
gem "grpc-tools"
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]
gem 'jbuilder', '~> 2.7'
gem 'erb', '~> 4.0'
gem "bootsnap", require: false

group :development, :test do
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
end

group :development do
  gem 'spring'
end
