# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: todo_service.proto for package 'todo_service'

require 'grpc'
require_relative './todo_service_pb'

module TodoService
  module TodoService
    # TodoService for managing tasks
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'todo_service.TodoService'

      rpc :AddTask, ::TodoService::AddTaskRequest, ::TodoService::AddTaskResponse
      rpc :AddTasksBulk, stream(::TodoService::AddTasksBulkRequest), ::TodoService::AddTasksBulkResponse
      rpc :ListTasks, ::TodoService::ListTasksRequest, stream(::TodoService::ListTasksResponse)
      rpc :UpdateTaskStatuses, stream(::TodoService::UpdateTaskStatusRequest), stream(::TodoService::UpdateTaskStatusResponse)
      rpc :DeleteTask, ::TodoService::DeleteTaskRequest, ::TodoService::DeleteTaskResponse
      rpc :GetTask, ::TodoService::GetTaskRequest, ::TodoService::GetTaskResponse
    end

    Stub = Service.rpc_stub_class
  end
end
